const ALL_RESTAURANTS = [
    {
        RowNo: 1,
        Id: 8444,
        PrevVendorId: 8444,
        Name: "Burger Shack - Kamaladi",
        VendorShortCut: "Burger Shack - Kamaladi",
        ShortName: "Burger Shack - Kamaladi",
        Address1: "Kamaladi",
        Address2: "Kamaladi",
        LocationLat: 27.710059,
        LocationLng: 85.319959,
        OpeningHours: "12:00 PM to 7:45 PM",
        OpeningTime: "12:00 PM",
        ClosingTime: "7:45 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Fast Food  | Burger",
        CuisineTags: " Burger | American | Lunch Hour Deals",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "4_151222081130._burger-shack-web-listing.jpg",
        VendorLogoName: "web_011019084817.logo.newrelease.burgershack_(1).jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/844/OriginalSize/4_151222081130._burger-shack-web-listing.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/844/OriginalSize/web_011019084817.logo.newrelease.burgershack_(1).jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/844/OriginalSize/4_151222081130._burger-shack-web-listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/844/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/844/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.2,
        VendorRatingStr: "4.20",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "12:00 PM to 7:45 PM",
    },
    {
        RowNo: 2,
        Id: 978,
        PrevVendorId: 978,
        Name: "Koto  - Durbarmarg",
        VendorShortCut: "Koto  - Durbarmarg",
        ShortName: "Koto  - Durbarmarg",
        Address1: "Durbarmarg",
        Address2: "Durbarmarg",
        LocationLat: 27.71157,
        LocationLng: 85.317375,
        OpeningHours: "11:30 AM to 9:30 PM",
        OpeningTime: "11:30 AM",
        ClosingTime: "9:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Japanese",
        CuisineTags: " Japanese",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "5_151222081218._koto-web.listing.jpg",
        VendorLogoName: "KOTO_011122101908.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/5_151222081218._koto-web.listing.jpg",
        VendorCoverImageName: "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/KOTO_011122101908.jpg",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/978/OriginalSize/5_151222081218._koto-web.listing.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/978/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "",
        Distance: 1.4,
        DeliveryDistanceStr: "Approx 1.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.91,
        VendorRatingStr: "3.91",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:30 AM to 9:30 PM",
    },
    {
        RowNo: 3,
        Id: 846,
        PrevVendorId: 846,
        Name: "Kathmandu Marriott",
        VendorShortCut: "Marriott",
        ShortName: "Kathmandu Marriott",
        Address1: "Naxal Kathmandu",
        Address2: "Naxal Kathmandu",
        LocationLat: 27.712945,
        LocationLng: 85.324154,
        OpeningHours: "11:00 AM to 9:00 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Bakery, Indian and Continental ",
        CuisineTags: " Indian | Bakery | Breakfast | Freebites | Father's Day | Father's Day Bkt",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "8_151222081509._ktm-marritot-web.listing.jpg",
        VendorLogoName: "web_211019101447.logo.newrelease.marriott.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/846/OriginalSize/8_151222081509._ktm-marritot-web.listing.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/846/OriginalSize/web_211019101447.logo.newrelease.marriott.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/846/OriginalSize/8_151222081509._ktm-marritot-web.listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/846/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/846/OriginalSize/",
        Distance: 1.4,
        DeliveryDistanceStr: "Approx 1.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.3,
        VendorRatingStr: "4.30",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 9:00 PM",
    },
    {
        RowNo: 4,
        Id: 308,
        PrevVendorId: 0,
        Name: "Le Trio (Durbar Marg)",
        VendorShortCut: "letrio2",
        ShortName: "Le Trio (Durbar Marg)",
        Address1: "Durbar Marg, Kathmandu",
        Address2: "Durbar Marg",
        LocationLat: 27.713377,
        LocationLng: 85.319909,
        OpeningHours: "11:00 AM to 9:00 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " MoMo | Multi Cuisine",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "7_151222081433._le-trio-web.listing.jpg",
        VendorLogoName: "letrio_081117061935.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/308/OriginalSize/7_151222081433._le-trio-web.listing.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/308/OriginalSize/letrio_081117061935.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/308/OriginalSize/7_151222081433._le-trio-web.listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/308/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/308/OriginalSize/",
        Distance: 1.5,
        DeliveryDistanceStr: "Approx 1.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.88,
        VendorRatingStr: "3.88",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 9:00 PM",
    },
    {
        RowNo: 5,
        Id: 269,
        PrevVendorId: 0,
        Name: "Fire And Ice Pizzeria",
        VendorShortCut: "fireNice",
        ShortName: "Fire And Ice Pizzeria",
        Address1: "Thamel, Kathmandu",
        Address2: "Thamel",
        LocationLat: 27.713579,
        LocationLng: 85.313516,
        OpeningHours: "11:00 AM to 6:00 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "6:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Italian",
        CuisineTags: " Italian | Pizza",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "2_151222080951._fire-and-ice-web.listing.jpg",
        VendorLogoName: "fireandice-web-logo_071117110319.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/269/OriginalSize/2_151222080951._fire-and-ice-web.listing.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/269/OriginalSize/fireandice-web-logo_071117110319.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/269/OriginalSize/2_151222080951._fire-and-ice-web.listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/269/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/269/OriginalSize/",
        Distance: 1.9,
        DeliveryDistanceStr: "Approx 2.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.03,
        VendorRatingStr: "4.03",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 6:00 PM",
    },
    {
        RowNo: 6,
        Id: 576,
        PrevVendorId: 0,
        Name: "Diplomat",
        VendorShortCut: "Diplomat",
        ShortName: "Diplomat",
        Address1: "Hotel Ambassador, Lazimpat",
        Address2: "Hotel Ambassador, Lazimpat",
        LocationLat: 27.718796,
        LocationLng: 85.317531,
        OpeningHours: "12:00 PM to 8:45 PM",
        OpeningTime: "12:00 PM",
        ClosingTime: "8:45 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Indian",
        CuisineTags: " Indian | Continental",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "9_151222081531._Diplomat-web.listing.jpg",
        VendorLogoName: "diplomat-website-logo_151018054041.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/576/OriginalSize/9_151222081531._Diplomat-web.listing.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/576/OriginalSize/diplomat-website-logo_151018054041.png",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/576/OriginalSize/9_151222081531._Diplomat-web.listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/576/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/576/OriginalSize/",
        Distance: 2.3,
        DeliveryDistanceStr: "Approx 2.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.9,
        VendorRatingStr: "4.90",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "12:00 PM to 8:45 PM",
    },
    {
        RowNo: 7,
        Id: 1027,
        PrevVendorId: 1027,
        Name: "4 Corners - Detroit Style Pizza",
        VendorShortCut: "4 Corners - Detroit Style Pizza",
        ShortName: "4 Corners - Detroit Style Pizza",
        Address1: "Sanepa",
        Address2: "Sanepa",
        LocationLat: 27.687932,
        LocationLng: 85.308291,
        OpeningHours: "12:30 PM to 9:00 PM",
        OpeningTime: "12:30 PM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Italian",
        CuisineTags: " Italian",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "6_151222081324._4-cornors-web.listing.jpg",
        VendorLogoName: "WhatsApp_Image_2022-01-25_at_10_250122043551.19.42_AM.jpeg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/6_151222081324._4-cornors-web.listing.jpg",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/WhatsApp_Image_2022-01-25_at_10_250122043551.19.42_AM.jpeg",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/6_151222081324._4-cornors-web.listing.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1027/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/1027/OriginalSize/",
        Distance: 2.9,
        DeliveryDistanceStr: "Approx 3.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.41,
        VendorRatingStr: "4.41",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "12:30 PM to 9:00 PM",
    },
    {
        RowNo: 8,
        Id: 326,
        PrevVendorId: 0,
        Name: "The Workshop Eatery - Jhamsikhel",
        VendorShortCut: "theworkshop",
        ShortName: "The Workshop Eatery - Jhamsikhel",
        Address1: "Bakhundole, Lalitpur",
        Address2: "",
        LocationLat: 27.683185,
        LocationLng: 85.311424,
        OpeningHours: "8:00 AM to 7:30 PM",
        OpeningTime: "8:00 AM",
        ClosingTime: "7:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "American",
        CuisineTags: " Burger | American | Breakfast",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "1_151222080829._workshop-eatery-web.listing.jpg",
        VendorLogoName: "Search_page@2x_(17)_161023061009.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/1_151222080829._workshop-eatery-web.listing.jpg",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/Search_page@2x_(17)_161023061009.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/1_151222080829._workshop-eatery-web.listing.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/326/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/326/OriginalSize/",
        Distance: 3.2,
        DeliveryDistanceStr: "Approx 3.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.17,
        VendorRatingStr: "4.17",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "8:00 AM to 7:30 PM",
    },
    {
        RowNo: 9,
        Id: 376,
        PrevVendorId: 0,
        Name: "Koto (Pulchowk)",
        VendorShortCut: "koto1",
        ShortName: "Koto (Pulchowk)",
        Address1: "Pulchowk, Lalitpur",
        Address2: "Pulchowk",
        LocationLat: 27.679521,
        LocationLng: 85.316756,
        OpeningHours: "11:30 AM to 9:00 PM",
        OpeningTime: "11:30 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Japanese",
        CuisineTags: " Asian | Japanese",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "5_151222081257._koto-web.listing.jpg",
        VendorLogoName: "KOTO_011122103304.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/376/OriginalSize/5_151222081257._koto-web.listing.jpg",
        VendorCoverImageName: "https://images.foodmandu.com//Images/Vendor/376/OriginalSize/KOTO_011122103304.jpg",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/376/OriginalSize/5_151222081257._koto-web.listing.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/376/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "",
        Distance: 3.5,
        DeliveryDistanceStr: "Approx 3.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.47,
        VendorRatingStr: "4.47",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:30 AM to 9:00 PM",
    },
    {
        RowNo: 10,
        Id: 232,
        PrevVendorId: 0,
        Name: "Le Trio",
        VendorShortCut: "letrio",
        ShortName: "Le Trio",
        Address1: "Jhamsikhel, Lalitpur",
        Address2: "Jhamsikhel",
        LocationLat: 27.675797,
        LocationLng: 85.314108,
        OpeningHours: "11:00 AM to 9:00 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " MoMo | Multi Cuisine",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "7_151222081350._le-trio-web.listing.jpg",
        VendorLogoName: "letrio_081117061917.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/232/OriginalSize/7_151222081350._le-trio-web.listing.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/232/OriginalSize/letrio_081117061917.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/232/OriginalSize/7_151222081350._le-trio-web.listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/232/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/232/OriginalSize/",
        Distance: 4.1,
        DeliveryDistanceStr: "Approx 4.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.83,
        VendorRatingStr: "3.83",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 9:00 PM",
    },
    {
        RowNo: 11,
        Id: 1555,
        PrevVendorId: 0,
        Name: "Bell Bar & Bistro",
        VendorShortCut: "Bell Bar & Bistro",
        ShortName: "Bell Bar & Bistro",
        Address1: "Jhamsikhel",
        Address2: "Jhamsikhel",
        LocationLat: 27.676344,
        LocationLng: 85.311293,
        OpeningHours: "1:00 PM to 9:00 PM",
        OpeningTime: "1:00 PM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Italian",
        CuisineTags: " Italian",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "web_250923104506.listing.bell_and_bistro.png",
        VendorLogoName: "Search_page@2x_(12)_260923072953.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1555/OriginalSize/web_250923104506.listing.bell_and_bistro.png",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1555/OriginalSize/Search_page@2x_(12)_260923072953.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1555/OriginalSize/web_250923104506.listing.bell_and_bistro.png",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1555/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/1555/OriginalSize/",
        Distance: 4.1,
        DeliveryDistanceStr: "Approx 4.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.0,
        VendorRatingStr: "4.00",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "1:00 PM to 9:00 PM",
    },
    {
        RowNo: 12,
        Id: 289,
        PrevVendorId: 0,
        Name: "Burger Shack - Jawalakhel",
        VendorShortCut: "Burger Shack - Jawalakhel",
        ShortName: "Burger Shack - Jawalakhel",
        Address1: "Jawalakhel, Lalitpur",
        Address2: "Jawalakhel",
        LocationLat: 27.672494,
        LocationLng: 85.313839,
        OpeningHours: "12:00 PM to 8:00 PM",
        OpeningTime: "12:00 PM",
        ClosingTime: "8:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Fast Food  | Burger",
        CuisineTags: " Burger | Fast Food",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "4_151222081103._burger-shack-web-listing.jpg",
        VendorLogoName: "burgershack-logo_180718094700.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/289/OriginalSize/4_151222081103._burger-shack-web-listing.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/289/OriginalSize/burgershack-logo_180718094700.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/289/OriginalSize/4_151222081103._burger-shack-web-listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/289/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/289/OriginalSize/",
        Distance: 4.6,
        DeliveryDistanceStr: "Approx 4.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.19,
        VendorRatingStr: "4.19",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "12:00 PM to 8:00 PM",
    },
    {
        RowNo: 13,
        Id: 676,
        PrevVendorId: 0,
        Name: "Le Trio - Maharajgunj",
        VendorShortCut: "Le Trio - Maharajgunj",
        ShortName: "Le Trio - Maharajgunj",
        Address1: "Maharajgunj",
        Address2: "Maharajgunj",
        LocationLat: 27.738444,
        LocationLng: 85.340328,
        OpeningHours: "11:00 AM to 8:00 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "8:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " MoMo | Multi Cuisine",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "7_151222081411._le-trio-web.listing.jpg",
        VendorLogoName: "2019-04-02_020419113129.jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/676/OriginalSize/7_151222081411._le-trio-web.listing.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/676/OriginalSize/2019-04-02_020419113129.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/676/OriginalSize/7_151222081411._le-trio-web.listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/676/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/676/OriginalSize/",
        Distance: 5.6,
        DeliveryDistanceStr: "Approx 5.5 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.14,
        VendorRatingStr: "4.14",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 8:00 PM",
    },
    {
        RowNo: 31,
        Id: 134,
        PrevVendorId: 0,
        Name: "Bajeko Sekuwa, Anamnagar",
        VendorShortCut: "bajekosekuwa2",
        ShortName: "Bajeko Sekuwa",
        Address1: "Anamnagar, Kathmandu",
        Address2: "Anamnagar",
        LocationLat: 27.697571,
        LocationLng: 85.328582,
        OpeningHours: "9:30 AM to 9:00 PM",
        OpeningTime: "9:30 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Nepali",
        CuisineTags: " Nepali",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "bajeko-Anamnager-web-listing_061117053619.jpg",
        VendorLogoName: "app_061021042602.logo.newrelease.bajekosekuwa.jpg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/134/OriginalSize/bajeko-Anamnager-web-listing_061117053619.jpg",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/134/OriginalSize/app_061021042602.logo.newrelease.bajekosekuwa.jpg",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/134/OriginalSize/bajeko-Anamnager-web-listing_061117053619.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/134/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.59,
        VendorRatingStr: "3.59",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "9:30 AM to 9:00 PM",
    },
    {
        RowNo: 32,
        Id: 1698,
        PrevVendorId: 0,
        Name: "Momoway",
        VendorShortCut: "Momoway",
        ShortName: "Momoway",
        Address1: "Kamalpokhari",
        Address2: "Kamalpokhari",
        LocationLat: 27.710173,
        LocationLng: 85.326597,
        OpeningHours: "10:00 AM to 9:00 PM",
        OpeningTime: "10:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Momo",
        CuisineTags: " MoMo",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "web_240823054636.listing-momo-way.png",
        VendorLogoName: "Search_page_240823054611.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1698/OriginalSize/web_240823054636.listing-momo-way.png",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1698/OriginalSize/Search_page_240823054611.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1698/OriginalSize/web_240823054636.listing-momo-way.png",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1698/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/1698/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.0,
        VendorRatingStr: "3.00",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "10:00 AM to 9:00 PM",
    },
    {
        RowNo: 33,
        Id: 1197,
        PrevVendorId: 1197,
        Name: "Traditional Comfort",
        VendorShortCut: "Traditionalcomfort",
        ShortName: "Traditional Comfort",
        Address1: "Kamalpokhari",
        Address2: "Kamalpokhari",
        LocationLat: 27.710936,
        LocationLng: 85.323172,
        OpeningHours: "8:30 AM to 9:00 PM",
        OpeningTime: "8:30 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Nepali",
        CuisineTags: " Nepali",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "WhatsApp_Image_2021-06-17_at_12_170621071121.52.06_PM.jpeg",
        VendorLogoName: "WhatsApp_Image_2021-06-17_at_12_170621071122.52.05_PM_(1).jpeg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/1197/OriginalSize/WhatsApp_Image_2021-06-17_at_12_170621071121.52.06_PM.jpeg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/1197/OriginalSize/WhatsApp_Image_2021-06-17_at_12_170621071122.52.05_PM_(1).jpeg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/1197/OriginalSize/WhatsApp_Image_2021-06-17_at_12_170621071121.52.06_PM.jpeg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/1197/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/1197/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.75,
        VendorRatingStr: "4.75",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "8:30 AM to 9:00 PM",
    },
    {
        RowNo: 34,
        Id: 1357,
        PrevVendorId: 1357,
        Name: "The Burger House & Crunchy Fried Chicken - Kamalpokhari ",
        VendorShortCut: "The Burger House & Crunchy Fried Chicken - Kamalpokhari",
        ShortName: "The Burger House & Crunchy Fried Chicken - Kamalpokhari",
        Address1: "Kamal Pokhari ",
        Address2: "Kamal Pokhari",
        LocationLat: 27.709286,
        LocationLng: 85.328264,
        OpeningHours: "10:00 AM to 9:00 PM",
        OpeningTime: "10:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " Multi Cuisine | Fast Food | Fried Chicken",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "WhatsApp_Image_2022-03-21_at_12_210322062145.04.40_PM.jpeg",
        VendorLogoName: "WhatsApp_Image_2022-03-21_at_12_210322062132.05.00_PM.jpeg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1357/OriginalSize/WhatsApp_Image_2022-03-21_at_12_210322062145.04.40_PM.jpeg",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1357/OriginalSize/WhatsApp_Image_2022-03-21_at_12_210322062132.05.00_PM.jpeg",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1357/OriginalSize/WhatsApp_Image_2022-03-21_at_12_210322062145.04.40_PM.jpeg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1357/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.76,
        VendorRatingStr: "3.76",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "10:00 AM to 9:00 PM",
    },
    {
        RowNo: 35,
        Id: 936,
        PrevVendorId: 936,
        Name: "Pawan Sweets- Durbarmarg",
        VendorShortCut: "Pawan Sweets",
        ShortName: "Pawan Sweets- Durbarmarg",
        Address1: "Teendhara Marga",
        Address2: "Teendhara Marga",
        LocationLat: 27.710168,
        LocationLng: 85.31836,
        OpeningHours: "9:30 AM to 7:30 PM",
        OpeningTime: "9:30 AM",
        ClosingTime: "7:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Sweets",
        CuisineTags: " Breakfast | Samosa",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "app_160320060141.listing.newrelease.pawan_sweets.jpg",
        VendorLogoName: "web_160320060201.logo.newrelease.pawan_sweets.jpg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/936/OriginalSize/web_160320060154.listing.newrelease.pawan_sweets.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/936/OriginalSize/web_160320060201.logo.newrelease.pawan_sweets.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/936/OriginalSize/app_160320060141.listing.newrelease.pawan_sweets.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/936/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/936/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.75,
        VendorRatingStr: "3.75",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "9:30 AM to 7:30 PM",
    },
    {
        RowNo: 36,
        Id: 1055,
        PrevVendorId: 1055,
        Name: "Angan - Kamalpokhari",
        VendorShortCut: "Angan - Kamalpokhari",
        ShortName: "Angan - Kamalpokhari",
        Address1: "Kamal pokhari",
        Address2: "Kamal pokhari",
        LocationLat: 27.709831,
        LocationLng: 85.327829,
        OpeningHours: "9:00 AM to 7:30 PM",
        OpeningTime: "9:00 AM",
        ClosingTime: "7:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Indian",
        CuisineTags: " Indian | Breakfast | Breakfast | Samosa",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "Web_031220085726.listing.angan.jpg",
        VendorLogoName: "new_angan_030822115134.jpg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/1055/OriginalSize/Web_031220085726.listing.angan.jpg",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1055/OriginalSize/new_angan_030822115134.jpg",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1055/OriginalSize/Web_031220085726.listing.angan.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1055/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/1055/OriginalSize/",
        Distance: 1.2,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.74,
        VendorRatingStr: "3.74",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "9:00 AM to 7:30 PM",
    },
    {
        RowNo: 25,
        Id: 844,
        PrevVendorId: 844,
        Name: "Burger Shack - Kamaladi",
        VendorShortCut: "Burger Shack - Kamaladi",
        ShortName: "Burger Shack - Kamaladi",
        Address1: "Kamaladi",
        Address2: "Kamaladi",
        LocationLat: 27.710059,
        LocationLng: 85.319959,
        OpeningHours: "12:00 PM to 7:45 PM",
        OpeningTime: "12:00 PM",
        ClosingTime: "7:45 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Fast Food  | Burger",
        CuisineTags: " Burger | American | Lunch Hour Deals",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "4_151222081130._burger-shack-web-listing.jpg",
        VendorLogoName: "web_011019084817.logo.newrelease.burgershack_(1).jpg",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/844/OriginalSize/4_151222081130._burger-shack-web-listing.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/844/OriginalSize/web_011019084817.logo.newrelease.burgershack_(1).jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/844/OriginalSize/4_151222081130._burger-shack-web-listing.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/844/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/844/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.2,
        VendorRatingStr: "4.20",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "12:00 PM to 7:45 PM",
    },
    {
        RowNo: 26,
        Id: 958,
        PrevVendorId: 958,
        Name: "Krishna Bakery & Confectionery",
        VendorShortCut: "Krishna Bakery & Confectionery",
        ShortName: "Krishna Bakery & Confectionery",
        Address1: "Kamalpokhari",
        Address2: "Kamalpokhari",
        LocationLat: 27.71044,
        LocationLng: 85.322539,
        OpeningHours: "8:00 AM to 6:00 PM",
        OpeningTime: "8:00 AM",
        ClosingTime: "6:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Bakery",
        CuisineTags: " Bakery | Cake",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "Web_300520055340.happy_lunch.Krishna_Bakery.jpg",
        VendorLogoName: "1_300520055332.Web.Logo..png",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/958/OriginalSize/Web_300520055340.happy_lunch.Krishna_Bakery.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/958/OriginalSize/1_300520055332.Web.Logo..png",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/958/OriginalSize/Web_300520055340.happy_lunch.Krishna_Bakery.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/958/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.8,
        VendorRatingStr: "3.80",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "8:00 AM to 6:00 PM",
    },
    {
        RowNo: 27,
        Id: 480,
        PrevVendorId: 0,
        Name: "Dalle Restaurant : Kamaladi",
        VendorShortCut: "dalle",
        ShortName: "Dalle Kamaladi",
        Address1: "Kamaladi",
        Address2: "Kamaladi",
        LocationLat: 27.71012,
        LocationLng: 85.319971,
        OpeningHours: "CLOSED NOW, Opens 11:15 AM to 11:15 AM",
        OpeningTime: "11:15 AM",
        ClosingTime: "4:00 PM",
        IsVendorClosed: true,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Momo",
        CuisineTags: " MoMo",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "weblisting-dalle_050523094401.png",
        VendorLogoName: "Search_page_(51)_290423035625.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/480/OriginalSize/weblisting-dalle_050523094401.png",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/480/OriginalSize/Search_page_(51)_290423035625.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/480/OriginalSize/weblisting-dalle_050523094401.png",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/480/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/480/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.73,
        VendorRatingStr: "3.73",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "CLOSED (Opens 11:15 AM to 4:00 PM)",
    },
    {
        RowNo: 28,
        Id: 1656,
        PrevVendorId: 0,
        Name: "The Hungry Owl",
        VendorShortCut: "The Hungry Owl",
        ShortName: "The Hungry Owl",
        Address1: "Hattisar",
        Address2: "Hattisar",
        LocationLat: 27.710443,
        LocationLng: 85.321179,
        OpeningHours: "10:00 AM to 9:30 PM",
        OpeningTime: "10:00 AM",
        ClosingTime: "9:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " Multi Cuisine | Local",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "web_210623053018.listing.hungryowl.png",
        VendorLogoName: "Search_page-8_210623053130.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/web_210623053018.listing.hungryowl.png",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/Search_page-8_210623053130.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/web_210623053018.listing.hungryowl.png",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1656/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 0.0,
        VendorRatingStr: "",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "10:00 AM to 9:30 PM",
    },
    {
        RowNo: 29,
        Id: 1198,
        PrevVendorId: 1198,
        Name: "Pan Asian Affair Restro & Bar",
        VendorShortCut: "Panasianaffair",
        ShortName: "Pan Asian Affair Restro & Bar",
        Address1: "Kamaladi",
        Address2: "Kamaladi",
        LocationLat: 27.709879,
        LocationLng: 85.318953,
        OpeningHours: "12:00 PM to 9:00 PM",
        OpeningTime: "12:00 PM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Pan Asian",
        CuisineTags: " Asian",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "Web-min_270621035104.jpg",
        VendorLogoName: "1_270621035102.App.Logo..jpg",
        VendorListingWebImageName: "https://foodmandu.com//Images/Vendor/1198/OriginalSize/Web-min_270621035104.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/1198/OriginalSize/1_270621035102.App.Logo..jpg",
        VendorLogoImageName: "https://foodmandu.com//Images/Vendor/1198/OriginalSize/Web-min_270621035104.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/1198/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/1198/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.55,
        VendorRatingStr: "4.55",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "12:00 PM to 9:00 PM",
    },
    {
        RowNo: 30,
        Id: 722,
        PrevVendorId: 0,
        Name: "The Bakery Cafe - Durbar Marg",
        VendorShortCut: "The Bakery Cafe",
        ShortName: "The Bakery Cafe - Durbar Marg",
        Address1: "Durbar Marg",
        Address2: "Durbar Marg",
        LocationLat: 27.709839,
        LocationLng: 85.318577,
        OpeningHours: "11:00 AM to 8:30 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "8:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " Multi Cuisine",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "app_120519031115.listing.newrelease.jpg",
        VendorLogoName: "app_120519031114.logo.newrelease.jpg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/722/OriginalSize/web_120519031115.listing.newrelease.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/722/OriginalSize/app_120519031114.logo.newrelease.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/722/OriginalSize/app_120519031115.listing.newrelease.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/722/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/722/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.15,
        VendorRatingStr: "4.15",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 8:30 PM",
    },
    {
        RowNo: 19,
        Id: 392,
        PrevVendorId: 0,
        Name: "Sajan Goth :: Kamaladi",
        VendorShortCut: "sajangoth2",
        ShortName: "Sajan Goth :: Kamaladi",
        Address1: "Kamaladi, Kathmandu",
        Address2: "Kamaladi",
        LocationLat: 27.709756,
        LocationLng: 85.320843,
        OpeningHours: "9:00 AM to 9:00 PM",
        OpeningTime: "9:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Indian",
        CuisineTags: " Indian | Sweets | Vegetarian | Samosa",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "sajangothp.jpg",
        VendorLogoName: "sajangoth-web-logo_081117064443.jpg",
        VendorListingWebImageName: "https://foodmandu.com//Images/Vendor/392/OriginalSize/2019-04-02_020419095426.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/392/OriginalSize/sajangoth-web-logo_081117064443.jpg",
        VendorLogoImageName: "https://foodmandu.com//Images/Vendor/392/OriginalSize/sajangothp.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/392/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/392/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.09,
        VendorRatingStr: "4.09",
        GridViewAvailable: true,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "9:00 AM to 9:00 PM",
    },
    {
        RowNo: 20,
        Id: 1729,
        PrevVendorId: 0,
        Name: "Gas O Fast",
        VendorShortCut: "Gas O Fast",
        ShortName: "Gas O Fast",
        Address1: "Kamal Pokhari",
        Address2: "Kamal Pokhari",
        LocationLat: 27.709077,
        LocationLng: 85.326742,
        OpeningHours: "10:00 AM to 9:00 PM",
        OpeningTime: "10:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Healthy | Ayurveda",
        CuisineTags: " Healthy",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "web_061023051057.listing-gas-o-fast.png",
        VendorLogoName: "Restaurant_Page_App_+_Web_061023051618.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1729/OriginalSize/web_061023051057.listing-gas-o-fast.png",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1729/OriginalSize/Restaurant_Page_App_+_Web_061023051618.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1729/OriginalSize/web_061023051057.listing-gas-o-fast.png",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1729/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/1729/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 0.0,
        VendorRatingStr: "",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "10:00 AM to 9:00 PM",
    },
    {
        RowNo: 21,
        Id: 339,
        PrevVendorId: 0,
        Name: "Bota Simply Mo:Mo - Kamal Pokhari",
        VendorShortCut: "Bota Simply Mo:Mo - Kamal Pokhari",
        ShortName: "Bota Simply Mo:Mo - Kamal Pokhari",
        Address1: "Kamal Pokhari, Kathmandu",
        Address2: "Kamal Pokhari",
        LocationLat: 27.709971,
        LocationLng: 85.32477,
        OpeningHours: "11:00 AM to 9:00 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "9:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Fast Food",
        CuisineTags: " MoMo | Fast Food",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "no-image.jpg",
        VendorLogoName: "WhatsApp_Image_2023-03-17_at_10_170323042532.09.21_AM.jpeg",
        VendorListingWebImageName: "https://foodmandu.com//Images/Vendor/339/OriginalSize/bota_050120022409.jpg",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/339/OriginalSize/WhatsApp_Image_2023-03-17_at_10_170323042532.09.21_AM.jpeg",
        VendorLogoImageName: "https://images.foodmandu.com//Images/Vendor/339/OriginalSize/no-image.jpg",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/339/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/339/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.73,
        VendorRatingStr: "3.73",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 9:00 PM",
    },
    {
        RowNo: 22,
        Id: 1004,
        PrevVendorId: 1004,
        Name: "Krishna Pauroti Bhandar",
        VendorShortCut: "Krishna Pauroti Bhandar",
        ShortName: "Krishna Pauroti Bhandar",
        Address1: "Kamal Pokhari",
        Address2: "Kamal Pokhari",
        LocationLat: 27.710226,
        LocationLng: 85.322415,
        OpeningHours: "8:00 AM to 8:00 PM",
        OpeningTime: "8:00 AM",
        ClosingTime: "8:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Bakery",
        CuisineTags: " Bakery",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "WhatsApp_Image_2020-08-09_at_11_090820065936.35.32_AM.jpeg",
        VendorLogoName: "WhatsApp_Image_2020-08-09_at_11_090820065950.35.30_AM.jpeg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/1004/OriginalSize/WhatsApp_Image_2020-08-09_at_11_090820065936.35.32_AM.jpeg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/1004/OriginalSize/WhatsApp_Image_2020-08-09_at_11_090820065950.35.30_AM.jpeg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/1004/OriginalSize/WhatsApp_Image_2020-08-09_at_11_090820065936.35.32_AM.jpeg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/1004/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/1004/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 3.89,
        VendorRatingStr: "3.89",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "8:00 AM to 8:00 PM",
    },
    {
        RowNo: 23,
        Id: 595,
        PrevVendorId: 0,
        Name: "Dragon Chinese Take Out",
        VendorShortCut: "Dragon Chinese Take Out",
        ShortName: "Dragon Chinese Take Out",
        Address1: "Marcopolo Business Hotel, Kamalpokhari",
        Address2: "Marcopolo Business Hotel, Kamalpokhari",
        LocationLat: 27.710343,
        LocationLng: 85.321967,
        OpeningHours: "11:00 AM to 8:45 PM",
        OpeningTime: "11:00 AM",
        ClosingTime: "8:45 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Chinese Cuisine",
        CuisineTags: " Chinese",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "listing_image_021118112438.jpg",
        VendorLogoName: "logo_(1)_021118112414.jpg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/595/OriginalSize/listing_image_021118112438.jpg",
        VendorCoverImageName: "https://foodmandu.com//Images/Vendor/595/OriginalSize/logo_(1)_021118112414.jpg",
        VendorLogoImageName: "https://foodmandu.com//Images/Vendor/595/OriginalSize/listing_image_021118112438.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/595/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/595/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.19,
        VendorRatingStr: "4.19",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:00 AM to 8:45 PM",
    },
    {
        RowNo: 24,
        Id: 1236,
        PrevVendorId: 1236,
        Name: "Tip Top - Kamal Pokhari ",
        VendorShortCut: "Tip Top",
        ShortName: "Tip Top - Kamal Pokhari",
        Address1: "Kamal Pokhari, Beside City Center ",
        Address2: "Kamal Pokhari, Beside City Center",
        LocationLat: 27.709452,
        LocationLng: 85.326673,
        OpeningHours: "11:30 AM to 6:00 PM",
        OpeningTime: "11:30 AM",
        ClosingTime: "6:00 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Indian",
        CuisineTags: " Indian | Sweets | Vegetarian | Samosa",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "web_130821071104.listing.newrelease.tiptop.jpg",
        VendorLogoName: "app_130821071105.logo.newrelease.tiptop.jpg",
        VendorListingWebImageName:
            "https://foodmandu.com//Images/Vendor/1236/OriginalSize/web_130821071104.listing.newrelease.tiptop.jpg",
        VendorCoverImageName:
            "https://foodmandu.com//Images/Vendor/1236/OriginalSize/app_130821071105.logo.newrelease.tiptop.jpg",
        VendorLogoImageName:
            "https://foodmandu.com//Images/Vendor/1236/OriginalSize/web_130821071104.listing.newrelease.tiptop.jpg",
        VendorLogoThumbPath: "https://foodmandu.com//Images/Vendor/1236/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://foodmandu.com//Images/Vendor/1236/OriginalSize/",
        Distance: 1.0,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 4.31,
        VendorRatingStr: "4.31",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "11:30 AM to 6:00 PM",
    },
    {
        RowNo: 281,
        Id: 16156,
        PrevVendorId: 0,
        Name: "The Hungry Owl",
        VendorShortCut: "The Hungry Owl",
        ShortName: "The Hungry Owl",
        Address1: "Hattisar",
        Address2: "Hattisar",
        LocationLat: 27.710443,
        LocationLng: 85.321179,
        OpeningHours: "10:00 AM to 9:30 PM",
        OpeningTime: "10:00 AM",
        ClosingTime: "9:30 PM",
        IsVendorClosed: false,
        AcceptsTakeoutOrder: false,
        AcceptsDeliveryOrder: true,
        IsVATApplicable: 0,
        ServiceCharge: 0.0,
        Cuisine: "Multi Cuisine",
        CuisineTags: " Multi Cuisine | Local",
        VendorType: "Restaurant",
        VendorKeyword: "",
        IsFavouriteVendor: 0,
        IsFavorite: 0,
        IsFeaturedVendor: false,
        VendorImageName: "web_210623053018.listing.hungryowl.png",
        VendorLogoName: "Search_page-8_210623053130.png",
        VendorListingWebImageName:
            "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/web_210623053018.listing.hungryowl.png",
        VendorCoverImageName:
            "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/Search_page-8_210623053130.png",
        VendorLogoImageName:
            "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/web_210623053018.listing.hungryowl.png",
        VendorLogoThumbPath: "https://images.foodmandu.com//Images/Vendor/1656/Logo",
        BannerImageOne: null,
        BannerImageTwo: null,
        VendorLogoPath: "https://images.foodmandu.com//Images/Vendor/1656/OriginalSize/",
        Distance: 1.1,
        DeliveryDistanceStr: "Approx 1.0 km",
        MinimumOrderAmount: 0.0,
        VendorRating: 0.0,
        VendorRatingStr: "",
        GridViewAvailable: false,
        DefaultView: "LIST",
        RecurringOrderAvailable: true,
        RecurringOrderAvailableDays: "",
        MaxRecurringOrderDate: "1900-01-01T00:00:00",
        DeliveryDuration: "",
        DeliveryChargeStr: "",
        DeliveryCharge: {
            color: null,
            font_size: 0,
            charge: "",
        },
        TotalCount: 729,
        PromoText: "",
        VendorNotice: "",
        VendorCloseLabel: "10:00 AM to 9:30 PM",
    },
];

export default ALL_RESTAURANTS;
